import { auth } from "@/lib/auth"
import { db } from "@/db"
import { adminSettings, posts, autoPilotRuns } from "@/db/schema"
import { generateTopic, generateCaption, generateHashtags } from "@/lib/openai-client"
import { generateImage } from "@/lib/image-gen"
import { put } from "@vercel/blob"
import { eq } from "drizzle-orm"
import { NextRequest } from "next/server"

export async function POST(req: NextRequest) {
  const session = await auth()
  if (!session) return new Response("Unauthorized", { status: 401 })

  const [settings] = await db.select().from(adminSettings).limit(1)
  if (!settings?.autopilotConfig) {
    return Response.json({ error: "Auto-pilot not configured" }, { status: 400 })
  }

  const config = settings.autopilotConfig

  // Create a run record
  const [run] = await db
    .insert(autoPilotRuns)
    .values({ status: "running" })
    .returning()

  try {
    // Step 1: Generate topic
    const topic = await generateTopic(config.topicContext ?? "lifestyle")

    // Step 2: Generate caption + hashtags
    const caption = await generateCaption({
      topic,
      style: config.style ?? "informational",
      language: "ru",
      accountContext: config.topicContext,
    })
    const hashtags = await generateHashtags(caption, "ru")

    // Step 3: Generate image
    const imageUrl = await generateImage({
      prompt: `High quality Instagram post image for: ${topic}. Professional, vibrant, engaging.`,
      aspectRatio: "1:1",
      resolution: "1K",
    })

    // Download and store in Vercel Blob
    const imgRes = await fetch(imageUrl)
    const imgBlob = await imgRes.blob()
    const stored = await put(
      `autopilot/${Date.now()}.jpg`,
      imgBlob,
      { access: "public", contentType: "image/jpeg" }
    )

    // Step 4: Create post
    const status = config.requireApproval ? "idea" : "scheduled"
    const publishDate = config.requireApproval ? null : getNextPublishDate()

    const [post] = await db
      .insert(posts)
      .values({
        status,
        postType: "image",
        caption,
        hashtags,
        mediaUrls: [stored.url],
        publishDate,
        isAutoGenerated: true,
      })
      .returning()

    // Update run record
    await db
      .update(autoPilotRuns)
      .set({
        status: "completed",
        topic,
        generatedCaption: caption,
        generatedHashtags: hashtags,
        imageUrl: stored.url,
        postId: post.id,
      })
      .where(eq(autoPilotRuns.id, run.id))

    return Response.json({ ok: true, postId: post.id, topic, requiresApproval: config.requireApproval })
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown"
    await db
      .update(autoPilotRuns)
      .set({ status: "failed", errorMessage: message })
      .where(eq(autoPilotRuns.id, run.id))
    return Response.json({ error: message }, { status: 500 })
  }
}

/** Schedule the post for the next optimal time (9:00 AM local next day). */
function getNextPublishDate(): Date {
  const d = new Date()
  d.setDate(d.getDate() + 1)
  d.setHours(9, 0, 0, 0)
  return d
}
