import {
  pgTable,
  text,
  timestamp,
  integer,
  real,
  jsonb,
  boolean,
} from "drizzle-orm/pg-core"
import { createId } from "@paralleldrive/cuid2"

// ─── Admin Settings (single row for the app owner) ───────────────────────────

export const adminSettings = pgTable("admin_settings", {
  id:               text("id").primaryKey().$defaultFn(() => createId()),
  email:            text("email").notNull().unique(),
  passwordHash:     text("password_hash").notNull(),
  openaiKeyEnc:     text("openai_key_enc"),
  apifyKeyEnc:      text("apify_key_enc"),
  imageGenKeyEnc:   text("image_gen_key_enc"),
  igUsername:       text("ig_username"),
  autopilotConfig:  jsonb("autopilot_config").$type<{
    enabled: boolean
    frequency: "daily" | "3x_week" | "weekly"
    topicContext: string
    style: "informational" | "entertaining" | "sales"
    requireApproval: boolean
  }>(),
  createdAt:        timestamp("created_at").defaultNow(),
  updatedAt:        timestamp("updated_at").defaultNow(),
})

// ─── Instagram Accounts (connected via Meta OAuth) ───────────────────────────

export const igAccounts = pgTable("ig_accounts", {
  id:              text("id").primaryKey().$defaultFn(() => createId()),
  igUserId:        text("ig_user_id").notNull().unique(),
  igUsername:      text("ig_username").notNull(),
  accessTokenEnc:  text("access_token_enc").notNull(),
  tokenExpiry:     timestamp("token_expiry"),
  profilePicUrl:   text("profile_pic_url"),
  createdAt:       timestamp("created_at").defaultNow(),
  updatedAt:       timestamp("updated_at").defaultNow(),
})

// ─── Posts (content plan) ─────────────────────────────────────────────────────

export const posts = pgTable("posts", {
  id:              text("id").primaryKey().$defaultFn(() => createId()),
  status:          text("status").notNull().default("idea"),
  // idea | draft | scheduled | published | failed
  postType:        text("post_type").notNull().default("image"),
  // image | carousel | reel | story
  caption:         text("caption"),
  hashtags:        text("hashtags").array(),
  mediaUrls:       text("media_urls").array(),
  musicUrl:        text("music_url"),
  publishDate:     timestamp("publish_date"),
  igPostId:        text("ig_post_id"),
  igPermalink:     text("ig_permalink"),
  errorMessage:    text("error_message"),
  isAutoGenerated: boolean("is_auto_generated").default(false),
  approvedAt:      timestamp("approved_at"),
  createdAt:       timestamp("created_at").defaultNow(),
  updatedAt:       timestamp("updated_at").defaultNow(),
})

// ─── Instagram Profile Snapshots (from Apify) ────────────────────────────────

export const igSnapshots = pgTable("ig_snapshots", {
  id:           text("id").primaryKey().$defaultFn(() => createId()),
  igUsername:   text("ig_username").notNull(),
  followers:    integer("followers"),
  following:    integer("following"),
  postsCount:   integer("posts_count"),
  avgLikes:     real("avg_likes"),
  avgComments:  real("avg_comments"),
  avgEr:        real("avg_er"),
  biography:    text("biography"),
  scrapedAt:    timestamp("scraped_at").defaultNow(),
})

// ─── Instagram Posts (scraped from Apify) ────────────────────────────────────

export const igPosts = pgTable("ig_posts", {
  id:        text("id").primaryKey().$defaultFn(() => createId()),
  igId:      text("ig_id").notNull().unique(),
  igUsername: text("ig_username"),
  caption:   text("caption"),
  mediaUrl:  text("media_url"),
  likes:     integer("likes").default(0),
  comments:  integer("comments").default(0),
  postType:  text("post_type"),
  shortcode: text("shortcode"),
  timestamp: timestamp("timestamp"),
  scrapedAt: timestamp("scraped_at").defaultNow(),
})

// ─── Competitors ──────────────────────────────────────────────────────────────

export const competitors = pgTable("competitors", {
  id:               text("id").primaryKey().$defaultFn(() => createId()),
  name:             text("name").notNull(),
  handle:           text("handle").notNull(),
  platform:         text("platform").notNull().default("instagram"),
  followers:        integer("followers"),
  avgEngagementRate: real("avg_engagement_rate"),
  postsPerWeek:     real("posts_per_week"),
  lastPostDate:     timestamp("last_post_date"),
  growth30d:        jsonb("growth_30d").$type<number[]>(),
  updatedAt:        timestamp("updated_at").defaultNow(),
})

// ─── Competitor Snapshots ─────────────────────────────────────────────────────

export const competitorSnapshots = pgTable("competitor_snapshots", {
  id:           text("id").primaryKey().$defaultFn(() => createId()),
  competitorId: text("competitor_id").notNull().references(() => competitors.id),
  followers:    integer("followers"),
  engagement:   real("engagement"),
  recordedAt:   timestamp("recorded_at").defaultNow(),
})

// ─── Auto-Pilot Runs ──────────────────────────────────────────────────────────

export const autoPilotRuns = pgTable("auto_pilot_runs", {
  id:               text("id").primaryKey().$defaultFn(() => createId()),
  status:           text("status").notNull().default("pending"),
  // pending | running | completed | failed
  topic:            text("topic"),
  generatedCaption: text("generated_caption"),
  generatedHashtags: text("generated_hashtags").array(),
  imageUrl:         text("image_url"),
  postId:           text("post_id").references(() => posts.id),
  errorMessage:     text("error_message"),
  createdAt:        timestamp("created_at").defaultNow(),
})
